#pragma once

#define TYPE GoodClass
BEGIN_CLASS(0x1111);
DECLARE_MID(DoThing);

MESSAGE_HANDLER_BEGIN(DoThing)
    int x = 1;
MESSAGE_HANDLER_END()

CAN_RECEIVE_BEGIN()
    CAN_RECEIVE_MID(DoThing)
CAN_RECEIVE_END()

RECEIVE_MESSAGE_BEGIN()
    RECEIVE_MESSAGE_ROUTE(DoThing)
RECEIVE_MESSAGE_END()

CLASSDEF()
#undef TYPE
