#pragma once
#define TYPE GoodChild
BEGIN_CLASS(0x9200);
INHERITS(Object);
SELF_MESSAGE_HANDLER_BEGIN_EXTERN(Object, Create)
    CALL_BASE();
    (void)Self;
MESSAGE_HANDLER_END()
SELF_MESSAGE_HANDLER_BEGIN_EXTERN(Object, Destroy)
    CALL_BASE();
    (void)Self;
MESSAGE_HANDLER_END()
CAN_RECEIVE_BEGIN()
    SELF_CAN_RECEIVE_MID_EXTERN(Object, Create)
    SELF_CAN_RECEIVE_MID_EXTERN(Object, Destroy)
CAN_RECEIVE_END()
RECEIVE_MESSAGE_BEGIN()
    SELF_RECEIVE_MESSAGE_ROUTE_EXTERN(Object, Create)
    SELF_RECEIVE_MESSAGE_ROUTE_EXTERN(Object, Destroy)
RECEIVE_MESSAGE_END()
CLASSDEF_INHERITS(Object)
#undef TYPE
