#pragma once
#define TYPE MyClass
BEGIN_CLASS(0x9090);
SELF_MESSAGE_HANDLER_BEGIN_EXTERN(SomeParent, Create)
    (void)Self;
MESSAGE_HANDLER_END()
CAN_RECEIVE_BEGIN()
    SELF_CAN_RECEIVE_MID_EXTERN(SomeParent, Create)
CAN_RECEIVE_END()
RECEIVE_MESSAGE_BEGIN()
    SELF_RECEIVE_MESSAGE_ROUTE_EXTERN(SomeParent, Create)
RECEIVE_MESSAGE_END()
CLASSDEF()
#undef TYPE
