#pragma once
#define TYPE MyClass
BEGIN_CLASS(0x9092);
DECLARE_MID(DoStuff, 0x01);
MESSAGE_HANDLER_BEGIN(DoStuff)
    CALL_BASE();
MESSAGE_HANDLER_END()
CAN_RECEIVE_BEGIN()
    CAN_RECEIVE_MID(DoStuff)
CAN_RECEIVE_END()
RECEIVE_MESSAGE_BEGIN()
    RECEIVE_MESSAGE_ROUTE(DoStuff)
RECEIVE_MESSAGE_END()
CLASSDEF()
#undef TYPE
