#pragma once
#define TYPE Late
BEGIN_CLASS(0x9099);
DECLARE_MID(Foo);
MESSAGE_HANDLER_BEGIN(Foo)
MESSAGE_HANDLER_END()
INHERITS(SomeParent);
CAN_RECEIVE_BEGIN()
    CAN_RECEIVE_MID(Foo)
CAN_RECEIVE_END()
RECEIVE_MESSAGE_BEGIN()
    RECEIVE_MESSAGE_ROUTE(Foo)
RECEIVE_MESSAGE_END()
CLASSDEF()
#undef TYPE
