#pragma once
#define TYPE DoubleCall
BEGIN_CLASS(0x9101);
INHERITS(Parent);
SELF_MESSAGE_HANDLER_BEGIN_EXTERN(Parent, Create)
    CALL_BASE();
    CALL_BASE();
    (void)Self;
MESSAGE_HANDLER_END()
CAN_RECEIVE_BEGIN()
    SELF_CAN_RECEIVE_MID_EXTERN(Parent, Create)
CAN_RECEIVE_END()
RECEIVE_MESSAGE_BEGIN()
    SELF_RECEIVE_MESSAGE_ROUTE_EXTERN(Parent, Create)
RECEIVE_MESSAGE_END()
CLASSDEF_INHERITS(Parent)
#undef TYPE
