#pragma once
#define TYPE GoodGO
BEGIN_CLASS(0xA111);
DECLARE_MID(DoStuff, 0x01);
MESSAGE_HANDLER_BEGIN(DoStuff)
    SPREAD_CONSUME(payload);
MESSAGE_HANDLER_END()
CAN_RECEIVE_BEGIN()
    CAN_RECEIVE_MID(DoStuff)
CAN_RECEIVE_END()
RECEIVE_MESSAGE_BEGIN()
    RECEIVE_MESSAGE_ROUTE(DoStuff)
RECEIVE_MESSAGE_END()
CLASSDEF()
#undef TYPE
