#pragma once
#define TYPE DupMid
BEGIN_CLASS(0xD120);
DECLARE_MID(Foo, 0x01);
DECLARE_MID(Bar, 0x01);
CAN_RECEIVE_BEGIN()
    CAN_RECEIVE_MID(Foo)
    CAN_RECEIVE_MID(Bar)
CAN_RECEIVE_END()
RECEIVE_MESSAGE_BEGIN()
    RECEIVE_MESSAGE_ROUTE(Foo)
    RECEIVE_MESSAGE_ROUTE(Bar)
RECEIVE_MESSAGE_END()
CLASSDEF()
#undef TYPE
