#pragma once

#include "ObjectContainer.h"

#define TYPE Object

SELF_MESSAGE_HANDLER_BEGIN(Create)
    (void)Self;
MESSAGE_HANDLER_END()

SELF_MESSAGE_HANDLER_BEGIN(Destroy)
    (void)Self;
MESSAGE_HANDLER_END()

SELF_MESSAGE_HANDLER_BEGIN(Serialize)
    (void)Self;
MESSAGE_HANDLER_END()

SELF_MESSAGE_HANDLER_BEGIN(Deserialize)
    (void)Self;
MESSAGE_HANDLER_END()

CAN_RECEIVE_BEGIN()
    SELF_CAN_RECEIVE_MID(Create)
    SELF_CAN_RECEIVE_MID(Destroy)
    SELF_CAN_RECEIVE_MID(Serialize)
    SELF_CAN_RECEIVE_MID(Deserialize)
CAN_RECEIVE_END()

RECEIVE_MESSAGE_BEGIN()
    SELF_RECEIVE_MESSAGE_ROUTE(Create)
    SELF_RECEIVE_MESSAGE_ROUTE(Destroy)
    SELF_RECEIVE_MESSAGE_ROUTE(Serialize)
    SELF_RECEIVE_MESSAGE_ROUTE(Deserialize)
RECEIVE_MESSAGE_END()

CLASSDEF()

#undef TYPE
