#pragma once

#include "../system/object/Self.h"
#include "scene_types.h"

#define TYPE SpinningCircle

BEGIN_CLASS(0x2201);
INHERITS(GameObject);

SELF_MESSAGE_HANDLER_DECL_EXTERN(Object, Create)
SELF_MESSAGE_HANDLER_DECL_EXTERN(Object, Destroy)
SELF_MESSAGE_HANDLER_DECL_EXTERN(GameObject, Update)
SELF_MESSAGE_HANDLER_DECL_EXTERN(GameObject, Render)

CAN_RECEIVE_BEGIN()
    SELF_CAN_RECEIVE_MID_EXTERN(Object, Create)
    SELF_CAN_RECEIVE_MID_EXTERN(Object, Destroy)
    SELF_CAN_RECEIVE_MID_EXTERN(GameObject, Update)
    SELF_CAN_RECEIVE_MID_EXTERN(GameObject, Render)
CAN_RECEIVE_END()

RECEIVE_MESSAGE_BEGIN()
    SELF_RECEIVE_MESSAGE_ROUTE_EXTERN(Object, Create)
    SELF_RECEIVE_MESSAGE_ROUTE_EXTERN(Object, Destroy)
    SELF_RECEIVE_MESSAGE_ROUTE_EXTERN(GameObject, Update)
    SELF_RECEIVE_MESSAGE_ROUTE_EXTERN(GameObject, Render)
RECEIVE_MESSAGE_END()

CLASSDEF_DECL_INHERITS(GameObject)

#undef TYPE
